-- Ensure you're using the correct database
USE alx_book_store;

-- Drop tables if they already exist to prevent errors
DROP TABLE IF EXISTS ORDER_DETAILS;
DROP TABLE IF EXISTS ORDERS;
DROP TABLE IF EXISTS CUSTOMERS;
DROP TABLE IF EXISTS BOOKS;
DROP TABLE IF EXISTS AUTHORS;

-- Create AUTHORS table
CREATE TABLE AUTHORS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    BIO TEXT
);

-- Create BOOKS table
CREATE TABLE BOOKS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(150) NOT NULL,
    GENRE VARCHAR(100),
    PRICE DECIMAL(10,2) NOT NULL,
    STOCK INT DEFAULT 0,
    AUTHOR_ID INT,
    FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS(ID)
);

-- Create CUSTOMERS table
CREATE TABLE CUSTOMERS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    PHONE VARCHAR(20),
    ADDRESS TEXT
);

-- Create ORDERS table
CREATE TABLE ORDERS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_ID INT NOT NULL,
    ORDER_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID)
);

-- Create ORDER_DETAILS table
CREATE TABLE ORDER_DETAILS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ORDER_ID INT NOT NULL,
    BOOK_ID INT NOT NULL,
    QUANTITY INT DEFAULT 1,
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ID),
    FOREIGN
